### ISSUE TITLE
Sifr icon missing und getting replaced by Colibre icon

### ISSUE THREAD

**Issue by ghost** [rizmut/libreoffice-style-sifr#7]
Hello,

first of all, thank you for your wonderful icon set. I'm using the SVG-version with Libre Office and have found a little bug. The icon for "Accept Change" seems to be the one from the Colibre icon set, not the correct one from the Sifr icon set the way it is displayed in the non-SVG version. Is there a way to fix that?

I keep the toolbar in Libre Office small, when I increase the size the correct icon is displayed.

I hope this issue wasn't already addressed elsewhere and I haven't seen it.

Thanks for reading :)

Sifr
<img width="191" alt="Sifr" src="https://user-images.githubusercontent.com/67192097/144748975-57896187-abe8-47a9-87f5-dc40edb01620.PNG">
Sifr.SVG
<img width="197" alt="Sifr (SVG)" src="https://user-images.githubusercontent.com/67192097/144748979-d5b00d5e-4097-480a-aaaa-233873d035f9.PNG">

PS: The size of my toolbar in Libre Office is set to small, so maybe the 16x16 icon is missing. When the toolbar is set to large, the icon is displayed correctly.

**Comment by rizmut** [comment]
I am pretty sure this issue is not related to completeness state of Sifr but rather than the way LibreOffice render SVG theme.I don't know why this unpleasant thing happened because I don't understand the source code. The LibreOffice developers already know this and there should have been a bug report as well. It's just that I haven't had time to look up the report number on LibreOffice's Bugzilla.

Anyway, thanks for reporting
